### ISSUE TITLE
Fix "Design/TooManyPublicMethods" issue in src/RestforceClient.php

### ISSUE THREAD

**Issue by jasonraimondi** [jasonraimondi/restforcephp#9]
The class RestforceClient has 12 public methods. Consider refactoring RestforceClient to keep number of public methods under 10.

https://codeclimate.com/github/jasonraimondi/restforcephp/src/RestforceClient.php#issue_57f2d6eb0614100001000017

**Comment by mjfaga** [comment]
Closing this... was created during a Code Climate configuration demo.
